# Roles
- name: kvmsible
  hosts: kvmsible
  user: root
  tasks:
  - name: update cache
    apt: update_cache=yes cache_valid_time=3600
  - name: Install kvm
    apt: name=qemu-kvm state=present
  - name: Install libvirt-bin
    apt: name=libvirt-bin state=present
  - name: Install virtinst
    apt: name=virtinst state=present
  - name: Install fail2ban
    apt: name=fail2ban state=present
  - name: Install unzip
    apt: name=unzip state=present
  - name: Install byobu
    apt: name=byobu state=present
  - name: Install build-essential
    apt: name=vim state=present
  - name: Install build-essential
    apt: name=rsync state=present
  - name: Install build-essential
    apt: name=git state=present
  - name: Install build-essential
    apt: name=shorewall state=present
  - name: Install build-essential
    apt: name=build-essential state=present
  - name: install packer
    script: packer.sh --some-arguments 1234
