# from galaxy
- src: deimosfs.packer
  packer_version: '0.7.5'
  packer_destination: '/usr/bin'


# from github, overriding the name and specifying a specific tag
- src: https://github.com/bennojoy/nginx
  version: master
  path: vagrant/roles/
  name: nginx_role
